spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testmbti
    username: postgres
    password: 0528
    data: classpath:/data.sql
  jpa:
    hibernate:
      ddl-auto: update